server {
    listen 80;
    location / {
        proxy_pass http://frontend:5173/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /account/ {
        proxy_pass http://auth-service:8000/account/;
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /blog/ {
        proxy_pass http://blog-service:8000/blog/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
