# Generated by Django 6.0.3 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodel",
            name="user_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
